### ISSUE TITLE
стр коллекции - уменьшить задержку перед появлением текста

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [MalahVitalij/rocket-luxurymod#24]
Сейчас же загружается фото телефона, потом ещё какое-то ожидание и только после проявляется текст.
http://prntscr.com/l6p5fc
http://prntscr.com/l6p5n3

**Comment by dchaika1990** [comment]
задержку убрал

**Comment by VladyslavKovalchuk** [comment]
в ие11 текст не появляется, а сразу прогружен
