### ISSUE TITLE
стр новости: не по тз

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [MalahVitalij/rocket-luxurymod#29]
картинки должны выезжать с левой стороны
так же, после первой загрузки страницы анимации появления картинок нет, они прогружены сразу, очистка кеша не помогает, в инкогнито тоже

**Comment by Sashamailrias** [comment]
Нужно починить "появления картинок нет, они прогружены сразу, очистка кеша не помогает, в инкогнито тоже"

**Comment by VladyslavKovalchuk** [comment]
теперь сломалась страница десктопная, и при ресайзе до планшетной и мобильной http://prntscr.com/lfg41s 
http://prntscr.com/lfg4hl
http://prntscr.com/lfg5af
исправить в соответствии с макетами
