### ISSUE TITLE
в кнопке "читать далее" другая стрелка

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [MalahVitalij/rocket-luxurymod#39]
http://prntscr.com/lbsr7k

**Comment by VladyslavKovalchuk** [comment]
при наведении стрелка должна поворачиваться в другую сторону, как тут кнопка "заказать" https://luxurymod-rocketcompany.netlify.com/kollection.html

**Comment by Username-Valeriy** [comment]
ты написал бы сразу что другая стрелка и другой эффект а то стрелку я поменялд а эффект нет
