### ISSUE TITLE
стр новости - поднять заголовок и текст

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [MalahVitalij/rocket-luxurymod#53]
http://joxi.ru/MAjxOBMT4KEGLm

**Comment by Username-Valeriy** [comment]
Сейчас заголовок и текст выравнивается горизонтально по центру, если задавать отступы, тогда на других экранах придется кучу всего дописывать и само выравнивание потеряет какую либо логику, сейчас хоть есть логика (центр блока)
