### ISSUE TITLE
Кнопка Вызов мастера

### ISSUE THREAD

**Issue by Sashamailrias** [MalahVitalij/rocket-luxurymod#76]
ХОВЕРЫ
https://prnt.sc/lfdm4o
https://prnt.sc/lfdmb2

**Comment by Username-Valeriy** [comment]
2 попап+ валидация

**Comment by VladyslavKovalchuk** [comment]
там после нажатия на кнопку она становится под углом, а должна стоять горизонтально http://prntscr.com/lfg0ek
